Networking\InitCmsBundle\Entity\Media:
  type: entity
  table: cms_media
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    locale:
      type: string
      length: 6
      nullable: true

# association already created in bundle extension
#  oneToMany:
#    galleryHasMedias:
#      targetEntity: Networking\InitCmsBundle\Entity\GalleryHasMedia
#      mappedBy: media
#      cascade: ["remove"]
#      orphan-removal: true
  manyToMany:
    tags:
      targetEntity: Networking\InitCmsBundle\Entity\Tag
      orphan-removal: true
      joinTable:
        name: cms_media_tag_media
        joinColumns:
          media_id:
            referencedColumnName: id
            onDelete: 'CASCADE'
        inverseJoinColumns:
          tag_id:
            referencedColumnName: id
            onDelete: 'CASCADE'
  lifecycleCallbacks:
    prePersist: [ prePersist ]
    preUpdate: [ preUpdate ]

